### PR TITLE
Fix storagePath if there is no Folder opened in workspace (Fixes #137)

### LINKED ISSUE #137: Path error when Open AtlasMap if there is no Folder opened for the workspace
I get "the path argument must be of type string. received type undefined" when running command AtlasMap: Open

OS: MacOS Mojave
VSCode: 1.36.1
Extension: 0.0.2(installed from marketplace)

### PR DESCRIPTION
**Pull request by jkopriva**
Signed-off-by: Josef Kopriva <jkopriva@redhat.com>

### CODE REVIEW

**Comment by jkopriva** [comment]
@apupier Feel free to comment, TS is new for me.

File: src/utils.ts [hunk 1]
```diff
@@ -33,4 +35,12 @@ function getViewPreference(): string {
 
 export function isUsingInternalView(): boolean {	
 	return getViewPreference() === BrowserType.Internal;
+}
+
+export function getStoragePath(context: vscode.ExtensionContext) {
+	if (context.storagePath == undefined){
+		return path.join(os.tmpdir());
```
Comment (apupier) [inline src/utils.ts]: what do you think to try to use ExtensionContext.globalStoragePath instead of os.tmpdir, it allows to stays in VS Code space. To check that it is always defined but i think yes given the description of the field.

https://code.visualstudio.com/api/extension-capabilities/common-capabilities#data-storage

File: src/utils.ts [hunk 2]
```diff
@@ -1,6 +1,8 @@
 "use strict";
 
 import * as detect from 'detect-port';
+import * as os from "os";
```
Comment (lhein) [inline src/utils.ts]: Can we use single quotes? I know in some spots we still use double quotes but we should try to only use single quotes if possible.

**Comment by jkopriva** [comment]
Hi @apupier, can you please review? There is an error with travis build - it does not seem related to this change.
Ad tests: I am also not sure how to write tests, but it could be part of https://github.com/jboss-fuse/vscode-atlasmap/issues/140, WDYT?

**Comment by apupier** [comment]
> There is an error with travis build - it does not seem related to this change.

you're right. Reported https://github.com/jboss-fuse/vscode-atlasmap/issues/141 , will fix it.  You will need to rebase on the fix after.



> Ad tests: I am also not sure how to write tests, but it could be part of #140, WDYT?

ok. Please add the test case.

**Comment by apupier** [comment]
> > There is an error with travis build - it does not seem related to this change.
> 
> you're right. Reported #141 , will fix it. You will need to rebase on the fix after.

fix merged on master, please rebase on master
